export const numericToAlpha3: Record<string, string> = {
  '004': 'AFG',
  '008': 'ALB',
  '010': 'ATA',
  '012': 'DZA',
  '016': 'ASM',
  '020': 'AND',
  '024': 'AGO',
  '028': 'ATG',
  '031': 'AZE',
  '032': 'ARG',
  '036': 'AUS',
  '040': 'AUT',
  '044': 'BHS',
  '048': 'BHR',
  '050': 'BGD',
  '051': 'ARM',
  '052': 'BRB',
  '056': 'BEL',
  '060': 'BMU',
  '064': 'BTN',
  '068': 'BOL',
  '070': 'BIH',
  '072': 'BWA',
  '074': 'BVT',
  '076': 'BRA',
  '084': 'BLZ',
  '086': 'IOT',
  '090': 'SLB',
  '092': 'VGB',
  '096': 'BRN',
  '100': 'BGR',
  '104': 'MMR',
  '108': 'BDI',
  '112': 'BLR',
  '116': 'KHM',
  '120': 'CMR',
  '124': 'CAN',
  '132': 'CPV',
  '136': 'CYM',
  '140': 'CAF',
  '144': 'LKA',
  '148': 'TCD',
  '152': 'CHL',
  '156': 'CHN',
  '158': 'TWN',
  '162': 'CXR',
  '166': 'CCK',
  '170': 'COL',
  '174': 'COM',
  '175': 'MYT',
  '178': 'COG',
  '180': 'COD',
  '184': 'COK',
  '188': 'CRI',
  '191': 'HRV',
  '192': 'CUB',
  '196': 'CYP',
  '203': 'CZE',
  '204': 'BEN',
  '208': 'DNK',
  '212': 'DMA',
  '214': 'DOM',
  '218': 'ECU',
  '222': 'SLV',
  '226': 'GNQ',
  '231': 'ETH',
  '232': 'ERI',
  '233': 'EST',
  '234': 'FRO',
  '238': 'FLK',
  '239': 'SGS',
  '242': 'FJI',
  '246': 'FIN',
  '248': 'ALA',
  '250': 'FRA',
  '254': 'GUF',
  '258': 'PYF',
  '260': 'ATF',
  '262': 'DJI',
  '266': 'GAB',
  '268': 'GEO',
  '270': 'GMB',
  '275': 'PSE',
  '276': 'DEU',
  '288': 'GHA',
  '292': 'GIB',
  '296': 'KIR',
  '300': 'GRC',
  '304': 'GRL',
  '308': 'GRD',
  '312': 'GLP',
  '316': 'GUM',
  '320': 'GTM',
  '324': 'GIN',
  '328': 'GUY',
  '332': 'HTI',
  '334': 'HMD',
  '336': 'VAT',
  '340': 'HND',
  '344': 'HKG',
  '348': 'HUN',
  '352': 'ISL',
  '356': 'IND',
  '360': 'IDN',
  '364': 'IRN',
  '368': 'IRQ',
  '372': 'IRL',
  '376': 'ISR',
  '380': 'ITA',
  '384': 'CIV',
  '388': 'JAM',
  '392': 'JPN',
  '398': 'KAZ',
  '400': 'JOR',
  '404': 'KEN',
  '408': 'PRK',
  '410': 'KOR',
  '414': 'KWT',
  '417': 'KGZ',
  '418': 'LAO',
  '422': 'LBN',
  '426': 'LSO',
  '428': 'LVA',
  '430': 'LBR',
  '434': 'LBY',
  '438': 'LIE',
  '440': 'LTU',
  '442': 'LUX',
  '446': 'MAC',
  '450': 'MDG',
  '454': 'MWI',
  '458': 'MYS',
  '462': 'MDV',
  '466': 'MLI',
  '470': 'MLT',
  '474': 'MTQ',
  '478': 'MRT',
  '480': 'MUS',
  '484': 'MEX',
  '492': 'MCO',
  '496': 'MNG',
  '498': 'MDA',
  '499': 'MNE',
  '500': 'MSR',
  '504': 'MAR',
  '508': 'MOZ',
  '512': 'OMN',
  '516': 'NAM',
  '520': 'NRU',
  '524': 'NPL',
  '528': 'NLD',
  '531': 'CUW',
  '533': 'ABW',
  '534': 'SXM',
  '535': 'BES',
  '540': 'NCL',
  '548': 'VUT',
  '554': 'NZL',
  '558': 'NIC',
  '562': 'NER',
  '566': 'NGA',
  '570': 'NIU',
  '574': 'NFK',
  '578': 'NOR',
  '580': 'MNP',
  '581': 'UMI',
  '583': 'FSM',
  '584': 'MHL',
  '585': 'PLW',
  '586': 'PAK',
  '591': 'PAN',
  '598': 'PNG',
  '600': 'PRY',
  '604': 'PER',
  '608': 'PHL',
  '612': 'PCN',
  '616': 'POL',
  '620': 'PRT',
  '624': 'GNB',
  '626': 'TLS',
  '630': 'PRI',
  '634': 'QAT',
  '638': 'REU',
  '642': 'ROU',
  '643': 'RUS',
  '646': 'RWA',
  '652': 'BLM',
  '654': 'SHN',
  '659': 'KNA',
  '660': 'AIA',
  '662': 'LCA',
  '663': 'MAF',
  '666': 'SPM',
  '670': 'VCT',
  '674': 'SMR',
  '678': 'STP',
  '682': 'SAU',
  '686': 'SEN',
  '688': 'SRB',
  '690': 'SYC',
  '694': 'SLE',
  '702': 'SGP',
  '703': 'SVK',
  '704': 'VNM',
  '705': 'SVN',
  '706': 'SOM',
  '710': 'ZAF',
  '716': 'ZWE',
  '724': 'ESP',
  '728': 'SSD',
  '729': 'SDN',
  '732': 'ESH',
  '740': 'SUR',
  '744': 'SJM',
  '748': 'SWZ',
  '752': 'SWE',
  '756': 'CHE',
  '760': 'SYR',
  '762': 'TJK',
  '764': 'THA',
  '768': 'TGO',
  '772': 'TKL',
  '776': 'TON',
  '780': 'TTO',
  '784': 'ARE',
  '788': 'TUN',
  '792': 'TUR',
  '795': 'TKM',
  '796': 'TCA',
  '798': 'TUV',
  '800': 'UGA',
  '804': 'UKR',
  '807': 'MKD',
  '818': 'EGY',
  '826': 'GBR',
  '831': 'GGY',
  '832': 'JEY',
  '833': 'IMN',
  '834': 'TZA',
  '840': 'USA',
  '850': 'VIR',
  '854': 'BFA',
  '858': 'URY',
  '860': 'UZB',
  '862': 'VEN',
  '876': 'WLF',
  '882': 'WSM',
  '887': 'YEM',
  '894': 'ZMB',
}

export const alpha3ToName: Record<string, string> = {
  'AFG': 'Afghanistan',
  'ALB': 'Albania',
  'ATA': 'Antarctica',
  'DZA': 'Algeria',
  'ASM': 'American Samoa',
  'AND': 'Andorra',
  'AGO': 'Angola',
  'ATG': 'Antigua and Barbuda',
  'AZE': 'Azerbaijan',
  'ARG': 'Argentina',
  'AUS': 'Australia',
  'AUT': 'Austria',
  'BHS': 'Bahamas',
  'BHR': 'Bahrain',
  'BGD': 'Bangladesh',
  'ARM': 'Armenia',
  'BRB': 'Barbados',
  'BEL': 'Belgium',
  'BMU': 'Bermuda',
  'BTN': 'Bhutan',
  'BOL': 'Bolivia, Plurinational State of',
  'BIH': 'Bosnia and Herzegovina',
  'BWA': 'Botswana',
  'BVT': 'Bouvet Island',
  'BRA': 'Brazil',
  'BLZ': 'Belize',
  'IOT': 'British Indian Ocean Territory',
  'SLB': 'Solomon Islands',
  'VGB': 'Virgin Islands, British',
  'BRN': 'Brunei Darussalam',
  'BGR': 'Bulgaria',
  'MMR': 'Myanmar',
  'BDI': 'Burundi',
  'BLR': 'Belarus',
  'KHM': 'Cambodia',
  'CMR': 'Cameroon',
  'CAN': 'Canada',
  'CPV': 'Cabo Verde',
  'CYM': 'Cayman Islands',
  'CAF': 'Central African Republic',
  'LKA': 'Sri Lanka',
  'TCD': 'Chad',
  'CHL': 'Chile',
  'CHN': 'China',
  'TWN': 'Taiwan, Province of China',
  'CXR': 'Christmas Island',
  'CCK': 'Cocos (Keeling) Islands',
  'COL': 'Colombia',
  'COM': 'Comoros',
  'MYT': 'Mayotte',
  'COG': 'Congo',
  'COD': 'Congo, The Democratic Republic of the',
  'COK': 'Cook Islands',
  'CRI': 'Costa Rica',
  'HRV': 'Croatia',
  'CUB': 'Cuba',
  'CYP': 'Cyprus',
  'CZE': 'Czechia',
  'BEN': 'Benin',
  'DNK': 'Denmark',
  'DMA': 'Dominica',
  'DOM': 'Dominican Republic',
  'ECU': 'Ecuador',
  'SLV': 'El Salvador',
  'GNQ': 'Equatorial Guinea',
  'ETH': 'Ethiopia',
  'ERI': 'Eritrea',
  'EST': 'Estonia',
  'FRO': 'Faroe Islands',
  'FLK': 'Falkland Islands (Malvinas)',
  'SGS': 'South Georgia and the South Sandwich Islands',
  'FJI': 'Fiji',
  'FIN': 'Finland',
  'ALA': 'Åland Islands',
  'FRA': 'France',
  'GUF': 'French Guiana',
  'PYF': 'French Polynesia',
  'ATF': 'French Southern Territories',
  'DJI': 'Djibouti',
  'GAB': 'Gabon',
  'GEO': 'Georgia',
  'GMB': 'Gambia',
  'PSE': 'Palestine, State of',
  'DEU': 'Germany',
  'GHA': 'Ghana',
  'GIB': 'Gibraltar',
  'KIR': 'Kiribati',
  'GRC': 'Greece',
  'GRL': 'Greenland',
  'GRD': 'Grenada',
  'GLP': 'Guadeloupe',
  'GUM': 'Guam',
  'GTM': 'Guatemala',
  'GIN': 'Guinea',
  'GUY': 'Guyana',
  'HTI': 'Haiti',
  'HMD': 'Heard Island and McDonald Islands',
  'VAT': 'Holy See (Vatican City State)',
  'HND': 'Honduras',
  'HKG': 'Hong Kong',
  'HUN': 'Hungary',
  'ISL': 'Iceland',
  'IND': 'India',
  'IDN': 'Indonesia',
  'IRN': 'Iran, Islamic Republic of',
  'IRQ': 'Iraq',
  'IRL': 'Ireland',
  'ISR': 'Israel',
  'ITA': 'Italy',
  'CIV': 'Côte d\'Ivoire',
  'JAM': 'Jamaica',
  'JPN': 'Japan',
  'KAZ': 'Kazakhstan',
  'JOR': 'Jordan',
  'KEN': 'Kenya',
  'PRK': 'Korea, Democratic People\'s Republic of',
  'KOR': 'Korea, Republic of',
  'KWT': 'Kuwait',
  'KGZ': 'Kyrgyzstan',
  'LAO': 'Lao People\'s Democratic Republic',
  'LBN': 'Lebanon',
  'LSO': 'Lesotho',
  'LVA': 'Latvia',
  'LBR': 'Liberia',
  'LBY': 'Libya',
  'LIE': 'Liechtenstein',
  'LTU': 'Lithuania',
  'LUX': 'Luxembourg',
  'MAC': 'Macao',
  'MDG': 'Madagascar',
  'MWI': 'Malawi',
  'MYS': 'Malaysia',
  'MDV': 'Maldives',
  'MLI': 'Mali',
  'MLT': 'Malta',
  'MTQ': 'Martinique',
  'MRT': 'Mauritania',
  'MUS': 'Mauritius',
  'MEX': 'Mexico',
  'MCO': 'Monaco',
  'MNG': 'Mongolia',
  'MDA': 'Moldova, Republic of',
  'MNE': 'Montenegro',
  'MSR': 'Montserrat',
  'MAR': 'Morocco',
  'MOZ': 'Mozambique',
  'OMN': 'Oman',
  'NAM': 'Namibia',
  'NRU': 'Nauru',
  'NPL': 'Nepal',
  'NLD': 'Netherlands',
  'CUW': 'Curaçao',
  'ABW': 'Aruba',
  'SXM': 'Sint Maarten (Dutch part)',
  'BES': 'Bonaire, Sint Eustatius and Saba',
  'NCL': 'New Caledonia',
  'VUT': 'Vanuatu',
  'NZL': 'New Zealand',
  'NIC': 'Nicaragua',
  'NER': 'Niger',
  'NGA': 'Nigeria',
  'NIU': 'Niue',
  'NFK': 'Norfolk Island',
  'NOR': 'Norway',
  'MNP': 'Northern Mariana Islands',
  'UMI': 'United States Minor Outlying Islands',
  'FSM': 'Micronesia, Federated States of',
  'MHL': 'Marshall Islands',
  'PLW': 'Palau',
  'PAK': 'Pakistan',
  'PAN': 'Panama',
  'PNG': 'Papua New Guinea',
  'PRY': 'Paraguay',
  'PER': 'Peru',
  'PHL': 'Philippines',
  'PCN': 'Pitcairn',
  'POL': 'Poland',
  'PRT': 'Portugal',
  'GNB': 'Guinea-Bissau',
  'TLS': 'Timor-Leste',
  'PRI': 'Puerto Rico',
  'QAT': 'Qatar',
  'REU': 'Réunion',
  'ROU': 'Romania',
  'RUS': 'Russian Federation',
  'RWA': 'Rwanda',
  'BLM': 'Saint Barthélemy',
  'SHN': 'Saint Helena, Ascension and Tristan da Cunha',
  'KNA': 'Saint Kitts and Nevis',
  'AIA': 'Anguilla',
  'LCA': 'Saint Lucia',
  'MAF': 'Saint Martin (French part)',
  'SPM': 'Saint Pierre and Miquelon',
  'VCT': 'Saint Vincent and the Grenadines',
  'SMR': 'San Marino',
  'STP': 'Sao Tome and Principe',
  'SAU': 'Saudi Arabia',
  'SEN': 'Senegal',
  'SRB': 'Serbia',
  'SYC': 'Seychelles',
  'SLE': 'Sierra Leone',
  'SGP': 'Singapore',
  'SVK': 'Slovakia',
  'VNM': 'Viet Nam',
  'SVN': 'Slovenia',
  'SOM': 'Somalia',
  'ZAF': 'South Africa',
  'ZWE': 'Zimbabwe',
  'ESP': 'Spain',
  'SSD': 'South Sudan',
  'SDN': 'Sudan',
  'ESH': 'Western Sahara',
  'SUR': 'Suriname',
  'SJM': 'Svalbard and Jan Mayen',
  'SWZ': 'Eswatini',
  'SWE': 'Sweden',
  'CHE': 'Switzerland',
  'SYR': 'Syrian Arab Republic',
  'TJK': 'Tajikistan',
  'THA': 'Thailand',
  'TGO': 'Togo',
  'TKL': 'Tokelau',
  'TON': 'Tonga',
  'TTO': 'Trinidad and Tobago',
  'ARE': 'United Arab Emirates',
  'TUN': 'Tunisia',
  'TUR': 'Türkiye',
  'TKM': 'Turkmenistan',
  'TCA': 'Turks and Caicos Islands',
  'TUV': 'Tuvalu',
  'UGA': 'Uganda',
  'UKR': 'Ukraine',
  'MKD': 'North Macedonia',
  'EGY': 'Egypt',
  'GBR': 'United Kingdom',
  'GGY': 'Guernsey',
  'JEY': 'Jersey',
  'IMN': 'Isle of Man',
  'TZA': 'Tanzania, United Republic of',
  'USA': 'United States',
  'VIR': 'Virgin Islands, U.S.',
  'BFA': 'Burkina Faso',
  'URY': 'Uruguay',
  'UZB': 'Uzbekistan',
  'VEN': 'Venezuela, Bolivarian Republic of',
  'WLF': 'Wallis and Futuna',
  'WSM': 'Samoa',
  'YEM': 'Yemen',
  'ZMB': 'Zambia',
}

const countryAliases: Record<string, string> = {
  'south korea': 'KOR',
  'korea': 'KOR',
  'north korea': 'PRK',
  'russia': 'RUS',
  'vietnam': 'VNM',
  'laos': 'LAO',
  'taiwan': 'TWN',
  'czech republic': 'CZE',
  'brunei': 'BRN',
}

const friendlyCountryNames: Record<string, string> = {
  KOR: 'South Korea',
  PRK: 'North Korea',
  RUS: 'Russia',
  VNM: 'Vietnam',
  LAO: 'Laos',
  TWN: 'Taiwan',
  CZE: 'Czechia',
  BRN: 'Brunei',
}

export function countryDisplayName(code: string): string {
  return friendlyCountryNames[code] ?? alpha3ToName[code] ?? code
}

export function parseCountryTokens(value: string): string[] {
  const tokens = value.split(',').map((token) => token.trim()).filter(Boolean)
  const entries = Object.entries(alpha3ToName)
  const codes = tokens.map((token) => {
    const upper = token.toUpperCase()
    if (/^[A-Z]{3}$/.test(upper) && alpha3ToName[upper]) return upper
    const normalized = token.toLowerCase()
    if (countryAliases[normalized]) return countryAliases[normalized]
    return entries.find(([, name]) => name.toLowerCase() === normalized)?.[0]
  }).filter((code): code is string => Boolean(code))
  return [...new Set(codes)]
}
